CSCfi/metax-api

src/metax_api/api/base/schemas/json_schema_dataset.json, src/metax_api/api/base/views/common_view.py, src/metax_api/api/base/views/contract_view.py, src/metax_api/api/base/views/dataset_view.py, src/metax_api/models/catalog_record.py, src/metax_api/services/__init__.py, src/metax_api/services/catalog_record_service.py, src/metax_api/services/common_service.py, src/metax_api/tests/api/base/apitests/test_api_catalog_records.py
...where feasible, due to tight coupling of views, models and serializers in Django REST
=> CSCMETAX-81: Separate business logic from views to services

requirements.txt, src/metax_api/__init__.py, src/metax_api/api/base/schemas/json_schema_datasetcatalog.json, src/metax_api/api/base/serializers/catalog_record_serializer.py, src/metax_api/cron/__init__.py, src/metax_api/cron/update_reference_data.py, src/metax_api/onappstart.py, src/metax_api/services/catalog_record_service.py, src/metax_api/settings.py, src/metax_api/tests/api/base/apitests/test_api_catalog_records.py, src/metax_api/tests/api/base/apitests/test_api_contracts.py, src/metax_api/tests/testdata/catalog_record_test_data_template.json, src/metax_api/tests/testdata/dataset_catalog_test_data_template.json, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json, src/metax_api/utils/__init__.py, src/metax_api/utils/redis.py, src/metax_api/utils/reference_data_service.py, src/metax_api/utils/utils.py
Do not merge until staging is updated!
=> CSCMETAX-109: reference data caching

src/metax_api/api/base/api_schemas/catalogrecord.json, swagger/schemas/catalogrecord.json, swagger/swagger.yaml
Accompanied with https://wiki.eduuni.fi/display/CSCMETAX/API+Documentation
=> CSCMETAX-139 update swagger docs

src/metax_api/api/base/api_schemas/catalogrecord.json, src/metax_api/api/base/serializers/catalog_record_serializer.py, src/metax_api/api/base/views/dataset_view.py, src/metax_api/models/catalog_record.py, src/metax_api/models/common.py, src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/base/apitests/test_api_catalog_records.py, swagger/swagger.yaml
... and some other gardening as a side product
=> CSCMETAX-149 owner id and api endpoint

.travis.yml, requirements.txt, src/metax_api/api/base/views/dataset_view.py, src/metax_api/api/base/xslt/datacite.xslt, src/metax_api/exceptions/http_exceptions.py, src/metax_api/services/catalog_record_service.py
Not finished, but hastened to get something to work with for Miika
=> CSCMETAX-51: [ADD] Datacite xml-transformation progress

src/metax_api/api/base/views/dataset_view.py, src/metax_api/api/base/xslt/datacite.xslt, src/metax_api/renderers/__init__.py, src/metax_api/renderers/renderers.py, src/metax_api/services/catalog_record_service.py, src/metax_api/settings.py, src/metax_api/tests/api/base/apitests/test_api_catalog_records.py, swagger/swagger.yaml
=> CSCMETAX-51: Datacite transformation

src/metax_api/api/base/router.py, src/metax_api/api/base/views/__init__.py, src/metax_api/api/base/views/directory_view.py, src/metax_api/models/contract.py, src/metax_api/models/file.py, src/metax_api/tests/api/base/apitests/files/write.py, swagger/swagger.yaml
More related actions todo in ticket https://jira.eduuni.fi/browse/CSCMETAX-189
=> CSCMETAX-188: Implement /directories?path={path}

src/metax_api/services/data_catalog_service.py, src/metax_api/utils/reference_data_service.py
...And treat labels in ES as objects
=> CSCMETAX 61: fix catalog relation refactor

src/metax_api/services/file_service.py, src/metax_api/tests/api/base/apitests/directories/read.py, src/metax_api/tests/api/base/apitests/files/write.py, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json
Previous implementation had some assumptions about conventions in IDA. Now makes a file hierarchy all the way from /.
=> CSCMETAX-61: Make directories more future proof

src/metax_api/models/catalog_record.py, src/metax_api/models/common.py, src/metax_api/models/directory.py, src/metax_api/models/file.py, src/metax_api/tests/models/__init__.py, src/metax_api/tests/models/common.py
Contains PR about single field post and delete, but that should be reviewed separately / first.
=> Cscmetax 61 improve field tracking

src/metax_api/api/base/schemas/att_dataset_schema.json, src/metax_api/api/base/schemas/kielipankki_harvester_dataset_schema.json, src/metax_api/api/base/schemas/syke_harvester_dataset_schema.json, src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/base/apitests/catalog_records/write.py, src/metax_api/tests/testdata/catalog_record_test_data_template_full.json, src/metax_api/tests/testdata/test_data.json
Note, requires reloading data since a field name has changed
=> Cscmetax 230 access restriction grounds type

src/metax_api/api/rest/base/serializers/catalog_record_serializer.py, src/metax_api/api/rest/base/serializers/common_serializer.py, src/metax_api/api/rest/base/serializers/file_serializer.py, src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/api/rest/base/views/files/read.py, src/metax_api/tests/api/rest/base/views/files/write.py
Note: Depends on PR 350.
Includes a couple of misc commits to clean up tests, and a fix related to updating files.
=> CSCMETAX-351: Parameter to expand relations

src/metax_api/api/rest/base/router.py, src/metax_api/api/rest/base/serializers/__init__.py, src/metax_api/api/rest/base/serializers/data_catalog_serializer.py, src/metax_api/api/rest/base/serializers/file_storage_serializer.py, src/metax_api/api/rest/base/views/__init__.py, src/metax_api/api/rest/base/views/file_storage_view.py, src/metax_api/initialdata/datacatalogs.json, src/metax_api/initialdata/filestorages.json, src/metax_api/management/commands/loadinitialdata.py, src/metax_api/models/file_storage.py, src/metax_api/onappstart.py, src/metax_api/tests/api/rest/base/views/datacatalogs/write.py, src/metax_api/tests/api/rest/base/views/filestorages/__init__.py, src/metax_api/tests/api/rest/base/views/filestorages/read.py, src/metax_api/tests/api/rest/base/views/filestorages/write.py, src/metax_api/tests/management/commands/loadinitialdata.py, swagger/swagger.yaml
Call python manage.py loadinitialdata any time to load catalogs and file storages from metax_api/initialdata.
=> CSCMETAX-348: Means to import production initial data

src/metax_api/api/oaipmh/base/metax_oai_server.py, src/metax_api/tests/api/oaipmh/__init__.py, src/metax_api/tests/api/oaipmh/minimal_api.py
Now the oai-pmh tests are also actually part of the test suite (added __init__). This omission also explains why test coverage was always going down when I was adding tests =)
=> CSCMETAX-280:[ADD] datacatalog harvesting

src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/models/catalog_record.py, src/metax_api/models/directory.py, src/metax_api/models/file.py, src/metax_api/services/catalog_record_service.py, src/metax_api/services/file_service.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/base/views/directories/read.py, src/metax_api/tests/testdata/fetch_and_update_datasets.py, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json, src/metax_api/tests/utils.py
Includes a few misc unrelated commits
=> CSCMETAX-412: File browsing and create optimizations

src/metax_api/api/rest/base/serializers/catalog_record_serializer.py, src/metax_api/api/rest/base/views/common_view.py, src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/exceptions/http_exceptions.py, src/metax_api/models/catalog_record.py, src/metax_api/services/callable_service.py, src/metax_api/services/common_service.py
Each commit should leave the app in working state. Made many commits in order to make it easier to review each step.
=> CSCMETAX-388: [ADD|FIX|REF] REMS add resources

docs/source/datasets.rst, src/metax_api/api/rest/base/schemas/att_dataset_schema.json, src/metax_api/exampledata/dataset_minimal.json, src/metax_api/initialdata/datacatalogs.json, src/metax_api/models/catalog_record.py, src/metax_api/services/catalog_record_service.py, src/metax_api/services/data_catalog_service.py, src/metax_api/services/datacite_service.py, src/metax_api/tests/api/oaipmh/minimal_api.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/testdata/catalog_record_test_data_template.json, src/metax_api/tests/testdata/catalog_record_test_data_template_full_att.json, src/metax_api/tests/testdata/catalog_record_test_data_template_full_ida.json, src/metax_api/tests/testdata/data_catalog_test_data_template.json, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json
* Fix reference data URIs
* Remove remote_resource.modified from being compulsory info
Note: requires reindexing of reference data. Has been done in metax-test already.
=> Cscmetax 480 485

docs/source/datasets.rst, src/metax_api/api/rest/base/schemas/att_dataset_schema.json, src/metax_api/api/rest/base/schemas/harvester_dataset_schema.json, src/metax_api/api/rest/base/schemas/ida_dataset_schema.json, src/metax_api/exampledata/dataset_minimal.json, src/metax_api/initialdata/datacatalogs.json, src/metax_api/models/catalog_record.py, src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/oaipmh/minimal_api.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/api/rest/base/views/directories/read.py, src/metax_api/tests/testdata/catalog_record_test_data_template.json, src/metax_api/tests/testdata/catalog_record_test_data_template_full_att.json, src/metax_api/tests/testdata/catalog_record_test_data_template_full_ida.json, src/metax_api/tests/testdata/data_catalog_test_data_template.json, src/metax_api/tests/testdata/test_data.json, src/metax_api/tests/utils.py
Reference datas changed related to this ticket: https://github.com/CSCfi/metax-ops/commit/4183d995b63315be3f72c571ba881d46427c5208
=> Cscmetax 486 simplify access types

src/metax_api/api/rpc/base/views/statistic_rpc.py, src/metax_api/services/statistic_service.py, src/metax_api/settings.py, swagger/swagger.yaml
=> CSCMETAX-640: [ADD/FIX] documented the statistics api and fixed

src/metax_api/models/catalog_record.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
date_removed under dataset_version_set
Add related test to write.py
New feature
=> CSCFAIRMETA-397-Add-date-removed-info-under-dataset-version-set: Add

src/metax_api/models/catalog_record.py, src/metax_api/services/rems_service.py, src/metax_api/settings.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
- Add reporter user to fetch all applications of dataset
- Applications are fetched by title since no other filter is
currently available
- Correct user for application closing is chosen according to
the application state
=> CSCFAIRMETA-311: [ADD] rems handling on	dataset deletion

src/metax_api/models/catalog_record.py, src/metax_api/services/rems_service.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
- Added reason to REMS close operation to give more informative
comment in closed applications
=> CSCFAIRMETA-314: [ADD] access type change closes REMS entities

src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/tests/testdata/fetch_and_update_datasets.py
- Previously all dataset were fetched and updated in fetch_and_update_datasets.py.
Fixed it to only fetch test dataset since that was the original idea of this script and 
had serious issues.
- Updated update_cr_directory_browsing_data api-call to only fetch non-deprecated
datasets because it broke down otherwise.
=> Cscfairmeta 669 fix deploy scripts

src/metax_api/tests/testdata/fetch_and_update_datasets.py
- Browsing data update crashed on PAS datasets because they are not deprecated on file deletion
=> CSCFAIRMETA-669: [FIX] only update test browsing data

src/metax_api/settings.py
- There is some problems when using the new ES version non-locally
but fix that issue later because it is only affecting the travis
tests
=> CSCFAIRMETA-710: [FIX] use demo ES in travis

src/metax_api/migrations/0026_auto_20200917_1615.py
- Add check whether metadata_owner_org or metadata_provider_org exists
=> CSCFAIRMETA-712-Issues-with-emails

src/metax_api/models/catalog_record.py, src/metax_api/models/common.py, src/metax_api/models/contract.py, src/metax_api/models/data_catalog.py, src/metax_api/models/directory.py, src/metax_api/models/file.py, src/metax_api/models/file_storage.py, src/metax_api/models/xml_metadata.py
- Rename models/common/delete to models/common/remove
- Make models listen to renamed function
- Set some foreign keys to null on delete
=> CSCFAIRMETA-771-Published-datasets-are-deleted-for-real

src/metax_api/models/catalog_record.py
- Add check if dataset is published before publishing to rabbitMQ
=> CSCFAIRMETA-764-Drafts-to-RabbitMQ

src/metax_api/models/catalog_record.py, src/metax_api/models/catalog_record_v2.py
- Testing can be done only in test-environment with etsin-test
=> CSCFAIRMETA-764-RabbitMQ

src/metax_api/initialdata/datacatalogs.json
-Add catalog rights according to
Service+permissions+for+data+catalogs
=> CSCFAIRMETA-791-Catalog_rights

src/metax_api/services/rabbitmq_service.py, src/metax_api/settings.py
- Bugfix: Run 'publish_to_TTV' only if user is 'ttv'
=> CSCFAIRMETA-799-RabbitMQ-to-TTV

src/metax_api/migrations/0028_auto_20201020_1010.py
=> Modified-migration-0028

src/metax_api/management/commands/loadinitialdata.py
=> Bugfix-with-loadinitialdata

src/metax_api/management/commands/loadinitialdata.py
- Add switch in case of dft catalog
=> Add-feature-switch-for-dft-catalog

src/metax_api/tests/testdata/fetch_and_update_datasets.py
* Add-feature-switch-for-dft-catalog
- Omit dft-catalog in fetch and update
* Add-feature-switch-for-dft-catalog
- Remove import
Co-authored-by: Katri Tegel <katri.tegel@gmail.com>
=> Merge Test to Stable

src/metax_api/initialdata/datacatalogs.json
-Add JYU catalog to test environments
=> CSCFAIRMETA-793-JYU-Metax-production-datacatalog-creation

src/metax_api/initialdata/datacatalogs.json
- Add read-rights for download service
=> CSCFAIRMETA-814-Access-for-download-service

src/metax_api/services/rabbitmq_service.py
-Rename django_settings to settings
=> CSCFAIRMETA-799-RabbitMQ-TTV-fix-settings

src/metax_api/settings/components/common.py
Add METAX_ENV to components via version control
=> Add_metax_env_variable_to_components

src/metax_api/management/commands/fix_file_counts_for_cr.py
- Recalculate byte_size and file_count for catalog record
=> CSCFAIRMETA-912-recalculate-bytesize-filecount-for-cr
