.githooks/pre-commit
Requires sym-linking action in metax-ops after clonging metax-api.
Hooks cannot be automatically included in cloned repositories to prevent execution of arbitrary code without user consent. The next best  thing is to include the hook-file, and symlink it to .git/hooks/
=> [ADD] .githooks directory to share common hooks

src/metax_api/api/base/views/common_view.py
Weird bug only manifested so far on staging when running gunicorn as a service.
=> CSCMETAX-61: [FIX] Specify encoding when opening json schema files

requirements.txt, src/.coveragerc, src/metax_api/api/base/views/common_view.py, src/metax_api/api/base/views/dataset_view.py, src/metax_api/settings.py, src/metax_api/utils/__init__.py, src/metax_api/utils/redis.py
Groundwork for using redis caching in the future. Helper methods to utilize redis sentinels using redis-py https://github.com/andymccurdy/redis-py.
Django redis-cache only supports master-slave setup for load balancing, where master failing renders cache unable to do new writes. Proper fail-over requires use of sentinels. redis-cache currently does not support them.
django-redis-sentinel-redux attempts to add support for sentinels, but has not been updated in 9 months, and does not work with latest versions of redis-cache.
=> CSCMETAX-25: Redis caching

src/metax_api/api/base/api_schemas/catalogrecord.json, src/metax_api/api/base/serializers/catalog_record_serializer.py, src/metax_api/api/base/views/dataset_view.py, src/metax_api/migrations/0002_create_json_indexes__keep.py, src/metax_api/models/__init__.py, src/metax_api/models/catalog_record.py, src/metax_api/tests/api/base/apitests/catalog_records/write.py, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json
Includes:
- Previous PR about checking that pref_id is unique within a data catalog
- New stuff about storing relations between the alternate records, and retrieving them in http responses
Does NOT include:
- Removing abilitiy to GET using preferred_identifier
- Raising error when preferred_identifier is available in ATT catalog, but already used in other catalogs
=> CSCMETAX 197: Alternate records handling

requirements.txt, src/metax_api/api/base/views/file_view.py, src/metax_api/models/catalog_record.py, src/metax_api/models/directory.py, src/metax_api/models/file.py, src/metax_api/models/xml_metadata.py, src/metax_api/services/common_service.py, src/metax_api/services/file_service.py, src/metax_api/tests/api/base/apitests/files/write.py
Includes a rather big overhaul of previous bulk create of files (file hierarchy creation). But now single create may use the same methods (they dont assume the request always concerns an entire directory only)
=> CSCMETAX-256: Single file post and delete

src/metax_api/models/catalog_record.py, src/metax_api/services/file_service.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/api/rest/base/views/files/write.py
Fix case when removing a top-level directory removed all files, even if dataset contain other sub-directories in the same tree.
Also:
- Refactor file-copy strategy from previous to new version
- Fix other issues discovered
- Add tests
=> CSCMETAX-61: Fix dir remove

src/metax_api/api/oaipmh/base/metax_oai_server.py, src/metax_api/api/rest/base/api_schemas/catalogrecord.json, src/metax_api/api/rest/base/router.py, src/metax_api/api/rest/base/serializers/catalog_record_serializer.py, src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/models/catalog_record.py, src/metax_api/services/catalog_record_service.py, src/metax_api/services/file_service.py, src/metax_api/tests/api/oaipmh/minimal_api.py, src/metax_api/tests/api/rest/base/views/common/read.py, src/metax_api/tests/api/rest/base/views/common/write.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/models/catalog_record.py, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json, swagger/swagger.yaml
- Instead of creating separate CatalogRecord objects of each new metadata version, always keep modifying the same record, but create a new table ResearchDatasetVersions, where research_dataset field is stored on each update to research_dataset.
- New dataset versions (files change) still create new CatalogRecords.
- Since we are now primarily operating always on the same CR, it does not make sense to use metadata_version_identifier for targeting a specific CR in the API, since it changes after updating research_dataset. Therefore, introduce new field 'identifier' to CatalogRecord, which will be the primary identifier required for interacting with a specific CR using the API. This identifier is located on the root-level of the CR.
- New API /datasets/<pid>/metadata_versions to list old …
=> CSCMETAX-350: [ADD|REF] Dataset versioning simplification

src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/testdata/contract_test_data_template.json, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json, src/metax_api/tests/utils.py
Decided not to include production data catalogs in current test data generation, as it quickly devolved into a clusterfuck with tests breaking...
What I would recommend instead, keep the current test data as is. Either create a separate script to copy (not move, just copy) existing datasets from testdata and push them to production catalogs during test env deployment if it is really important to have data in those datalogs already. The catalogs themselves can be browsed in test envs already anyway.
Or even better, wait until we have real IDA projects as files test data, and create test datasets out of those, and store into related production catalogs.
=> CSCMETAX 374, 372, 61: Improve testdata

src/metax_api/api/rest/base/router.py, src/metax_api/api/rest/base/serializers/catalog_record_serializer.py, src/metax_api/api/rest/base/serializers/common_serializer.py, src/metax_api/api/rest/base/serializers/directory_serializer.py, src/metax_api/api/rest/base/serializers/file_serializer.py, src/metax_api/api/rest/base/views/api_error_view.py, src/metax_api/api/rest/base/views/common_view.py, src/metax_api/api/rest/base/views/contract_view.py, src/metax_api/api/rest/base/views/data_catalog_view.py, src/metax_api/api/rest/base/views/dataset_view.py, src/metax_api/api/rest/base/views/directory_view.py, src/metax_api/api/rest/base/views/file_storage_view.py, src/metax_api/api/rest/base/views/file_view.py, src/metax_api/services/catalog_record_service.py, src/metax_api/services/file_service.py, src/metax_api/tests/api/rest/base/views/common/read.py, src/metax_api/tests/api/rest/base/views/directories/read.py, swagger/swagger.yaml
In short, supported API's:
- all common GET list, and GET detail, i.e. /files/1?fields=x,y
- file browsing /directories/pid/files?file_fields=x,y&directory_fields=x,y
- /datasets/pid?file_details&file_fields=x,y&directory_fields=x,y
=> CSCMETAX-371: [ADD] Return specified fields only from various GET api's

docs/source/datasets.rst, docs/source/quick_start.rst, src/metax_api/api/rest/base/views/common_view.py, src/metax_api/api/rest/base/views/directory_view.py, src/metax_api/api/rest/base/views/schema_view.py, src/metax_api/api/rpc/base/__init__.py, src/metax_api/api/rpc/base/common_rpc.py, src/metax_api/api/rpc/base/dataset_rpc.py, src/metax_api/api/rpc/base/router.py, src/metax_api/api/rpc/base/views/__init__.py, src/metax_api/api/rpc/base/views/common_rpc.py, src/metax_api/api/rpc/base/views/dataset_rpc.py, src/metax_api/exampledata/dataset_minimal.json, src/metax_api/permissions/permissions.py, src/metax_api/settings.py, src/metax_api/tests/api/rpc/base/views/__init__.py, src/metax_api/tests/api/rpc/base/views/dataset_rpc.py, swagger/swagger.yaml
Added base for RPC apis, and the first RPC api /rpc/datasets/get_minimal_dataset_template.
Needs updated metax-ops for altered API_PERMISSIONS object in app_config. Permissions for RPC can be set per RPC method.
=> CSCMETAX-436: RPC api + get example minimal dataset

docs/source/datasets.rst, docs/source/general.rst
Changes mostly to make schemas and schema validation errors easier to reason about.
- Move schema file links from general section to sections where they are more relevant
- Add "common schema validation errors" section for hard-to-decipher errors and tips
- Change dataset reference data table to contain info when a relation is an array
=> CSCMETAX-61: [ADD] Improve docs

src/metax_api/models/catalog_record.py, src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/utils/utils.py, swagger/swagger.yaml
* Fixed: Metax API crashes when creating a dataset into a harvester catalog while omitting pid
* Filter datasets by data catalog
=> Cscmetax 498 509

.travis-deploy.sh
* This PR needs to be first accepted: https://github.com/CSCfi/metax-ops/pull/6 . NOTE: Do not accept before https://github.com/CSCfi/metax-api/pull/390 is accepted since otherwise that PR would fail in Travis (would try to build the docs)
* Assuming metax test and stable domain names aren't a big secret
* Other way to do this would be to move all server_domain_name ansible variables to publiclly available inventory files
* Third way would be to set server_domain_name values as env variable and use that in the target env.
=> Cscmetax 506 docs building fails

requirements.txt, src/metax_api/middleware/request_logging.py, src/metax_api/onappstart.py, src/metax_api/services/statistic_service.py, src/metax_api/settings.py, src/metax_api/utils/utils.py, src/metax_api/views/secure/secure_view.py
Facilities to do json-logging in metax-app. Some initial logs to get into testing:
- http request start and end
- process start
- secure_view (login page)
metax-test should have related filebeat etc installed and configured, so safe to merge whenever.
=> CSCMETAX-524: structured logging

src/metax_api/middleware/identifyapicaller.py
- Do not verify a local request made to apache for validating bearer token
=> CSCMETAX-536: [FIX]

src/metax_api/renderers/renderers.py
- When debug is false and json is requested from api using Accept-header 'text/html' (e.g. browser), fix encoding of some characters.
=> CSCMETAX-535: [REF]

src/metax_api/api/rest/base/schemas/att_dataset_schema.json, src/metax_api/api/rest/base/schemas/ida_dataset_schema.json, src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
Licenses can be outside reference data for att and ida datasets but
either license identifier or url must be provided. Custom url can also
be provided when using identifier.
=> CSCMETAX-584: [ADD] Support for licenses outside reference data

src/metax_api/models/catalog_record.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
- When dataset is deprecated, Metax closes all REMS related entities
same as in deletion
- Added new tests and did some refactoring for the old REMS tests
=> CSCFAIRMETA-312: [ADD] deprecation closes REMS entities

src/metax_api/middleware/identifyapicaller.py, src/metax_api/models/catalog_record.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
[ADD]owner can update datasets
=> CSCFAIRMETA-433-Draft-datasets-can-be-updated-only-by-dataset-owner

src/metax_api/models/catalog_record.py, src/metax_api/services/catalog_record_service.py, src/metax_api/settings.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
Create new query parameter ?draft
Create feature switch for draft datasets
Save drafts without preferred identifier
Do not publish into publish into rabbitmq,
rems or datacite.
=> CSCFAIRMETA-437: [ADD] Allow-creating-new-datasets-into-draft-state

src/metax_api/api/rest/base/serializers/catalog_record_serializer.py, src/metax_api/models/catalog_record.py, src/metax_api/tests/api/rest/base/views/datasets/write.py
- access_granter information is now provided in a field
- field change validation is moved from serializer to models to
enable this feature
- new test to ensure that there are no changes in access_granter
when license is updated because this is a special case
=> CSCFAIRMETA-536: [FIX] access_granter is handled as a field

src/metax_api/api/rest/base/views/common_view.py
an object for updating, in order to properly lock the row in DB
=> CSCFAIRMETA-551: [ADD] Use select_for_update() method when retrieving

src/metax_api/api/rest/base/api_schemas/catalogrecord.json, swagger/v1/swagger.yaml
- v1 swagger remote references were not updated to point to v1 api-
schemas. This was discovered only after running deploy_nginx.
- Api-schemas had some extra trailing commas which caused swagger to
not showing the model
=> Merge pkg update to stable: v1.7.1-rc3

src/metax_api/services/catalog_record_service.py, src/metax_api/tests/api/rest/base/views/datasets/read.py, src/metax_api/tests/api/rest/v2/views/datasets/read.py, swagger/v1/swagger.yaml, swagger/v2/swagger.yaml
Creating this PR already but should be merged only after 565
=> CSCFAIRMETA-566: [ADD] filter datasets by their api version

requirements.txt
- The old version of the client didn't get installed eventually
because of the wrong order of the library installation
=> CSCFAIRMETA-212: [FIX] change order in requirements

src/metax_api/models/catalog_record.py, src/metax_api/models/catalog_record_v2.py, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/api/rest/v2/views/datasets/__init__.py, src/metax_api/tests/api/rest/v2/views/datasets/api_version_lock.py, src/metax_api/tests/api/rest/v2/views/datasets/drafts.py, src/metax_api/tests/api/rest/v2/views/datasets/write.py
Make issued_date mandatory field for ida and att-catalogs
If issued_date is not set, todays date is filled in
If issued_date is empty, error is returned
=> CSCFAIRMETA-639-Issued-date

src/metax_api/api/rpc/base/views/elasticsearch_rpc.py, src/metax_api/settings.py, src/metax_api/utils/reference_data_loader.py
- Correctly call elasticsearch when request comes to _mapping endpoint
- Local tests can be run against local elasticsearch which reduces the
population time
- Follow naming convention in refdata loader with non-internal
functions
=> CSCFAIRMETA-710: [FIX] _mapping endpoint and ES in testcases

.travis-deploy.sh, src/metax_api/api/rest/base/schemas/att_dataset_schema.json, src/metax_api/api/rest/base/schemas/harvester_dataset_schema.json, src/metax_api/api/rest/base/schemas/ida_dataset_schema.json, src/metax_api/api/rest/v2/api_schemas/ida_dataset_schema.json, src/metax_api/api/rest/v2/schemas/att_dataset_schema.json, src/metax_api/api/rest/v2/schemas/harvester_dataset_schema.json, src/metax_api/api/rest/v2/schemas/ida_dataset_schema.json, src/metax_api/settings.py, src/metax_api/tests/testdata/generate_test_data.py, src/metax_api/tests/testdata/test_data.json
- These mostly concern test data, but should be updated still
=> CSCFAIRADM-337: [ADD] Update domain references

src/metax_api/models/catalog_record_v2.py, src/metax_api/tests/api/rest/v2/views/datasets/drafts.py
- In merge_draft take preservation_state from draft cr
=> CSCFAIRMETA-704 [FIX] merge-draft-does-not-save-changes

src/metax_api/tests/api/rest/v2/views/datasets/drafts.py
- Move handling of next_draft directly under v1
- Change models/common def delete to delete directly
- models/common def remove handles 'deleting' of datasets
=> CSCFAIRMETA-676-cannot-delete-next-draft

src/metax_api/services/file_service.py, src/metax_api/tests/api/rest/base/views/files/read.py, src/metax_api/tests/api/rest/v2/views/files/read.py, swagger/v1/swagger.yaml, swagger/v2/swagger.yaml
- Replace urn with pid in return
- Describe new parameters in swagger
=> CSCFAIRMETA-760-Return-pids-instead-of-urns

src/metax_api/api/rest/base/serializers/data_catalog_serializer.py, src/metax_api/tests/api/rest/base/views/datacatalogs/write.py
- Name in publisher is required but it is now populated from ref
data if valid identifier for organisation is given
=> CSCFAIRMETA-662: [FIX] publisher name validation

AUTHORS, README.md
- Update the Travis badges so that they link to travis-ci.com instead of the old travis-ci.org
- Also update license and authors info
=> CSCFAIRADM-430: Update Travis links (.com) 

src/metax_api/models/catalog_record_v2.py, src/metax_api/tests/api/rpc/v2/views/dataset_rpc.py
- Prevents creating a new dataset version if there exists a draft
=> CSCFAIRMETA-701: [FIX] crash on v2 dataset rpc api

src/metax_api/models/catalog_record.py, src/metax_api/services/datacite_service.py, src/metax_api/settings/.env.template, src/metax_api/tests/api/rest/base/views/datasets/write.py, src/metax_api/tests/api/rest/v2/views/datasets/write.py, src/metax_api/utils/utils.py
- Add a check for identifiers from remote datasets (whether those are DOIs and not Metax-generated DOIs)
- Add a check that remote datasets with DOI are
validated against datacite
=> CSCFAIRMETA-890-DOI-as-pref-identifier

.travis.yml
flake8 fails CI-builds, this is not intended behavior from Python linter
=> delete flake8 check from travis.

src/metax_api/management/commands/load_data_to_TTV.py
- Fetch and publish all existing datasets into, and only to, TTV-operations queue
=> CSCFAIRMETA-954-publish-records-to-TTV
